version: '3'

services:
  db:
    container_name: ecommerce-serie-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: commandmaker
    ports:
      - "3600:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    container_name: ecommerce-serie-pma
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: commandmaker
      PMA_USER: root
      PMA_PASSWORD: commandmaker
      PMA_HOST: db
    networks:
      - dev
  nginx:
    container_name: ecommerce-serie-web
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev
  php:
    container_name: ecommerce-serie-php
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./docker/images/php
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    networks:
      - dev
  mail:
    image: mailhog/mailhog
    ports:
      - "1080:8025"
    networks:
      - dev
  sass:
    container_name: ecommerce-serie-sass
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./docker/images/sass
    volumes:
      - .:/opt/src

volumes:
  db-data:

networks:
  dev:
    driver: bridge
